spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:testDriver
spring.datasource.driverClassName= org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#The below line ensures that the Query written in the data.sql file is runned after the table is created
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update